apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: saicharan-deployment
  namespace: saicharan  
spec:
  selector:
    matchLabels:
      app: saicharan
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: saicharan
    spec:
      containers:
      - name: saicharan
        image: 349948765351.dkr.ecr.ap-south-1.amazonaws.com/saicharan:latest
        ports:
        - containerPort: 80

