apiVersion: v1
kind: Service
metadata:
  name: saicharan-service
  namespace: saicharan  
spec:
  type: LoadBalancer
  selector:
    app: saicharan
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

